version: "2.1"
services:
  postgres_orchestration:
    image: postgres:latest
    container_name: postgres_orchestration
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=magic
      - POSTGRES_DB=orchestration
    ports:
      - 5432:5432
    command: [ "postgres", "-c", "log_statement=all" ]
    volumes:
      - ./infrastructure/db/postgres/init/db/init.sql:/docker-entrypoint-initdb.d/init.sql
  migration_connector_hub_metadata:
    image: boxfuse/flyway:latest
    container_name: flyway_migration_connector_hub_metadata
    volumes:
      - ./infrastructure/db/postgres/migrations/connector_hub/metadata:/flyway/sql
      - ./infrastructure/db/postgres/bin:/flyway/bin
    entrypoint: [ "bash", "/flyway/bin/wait-for-it.sh", "postgres_orchestration:5432", "--", "flyway" ]
    command: -url=jdbc:postgresql://postgres_orchestration/orchestration -schemas=connector_hub_metadata -user=root -password=magic migrate
    depends_on:
      - postgres_orchestration
  migration_connector_hub_connections:
    image: boxfuse/flyway:latest
    container_name: flyway_migration_connector_hub_connections
    volumes:
      - ./infrastructure/db/postgres/migrations/connector_hub/connections:/flyway/sql
      - ./infrastructure/db/postgres/bin:/flyway/bin
    entrypoint: [ "bash", "/flyway/bin/wait-for-it.sh", "postgres_orchestration:5432", "--", "flyway" ]
    command: -url=jdbc:postgresql://postgres_orchestration/orchestration -schemas=connector_hub_connections -user=root -password=magic migrate
    depends_on:
      - postgres_orchestration
