apiVersion: "v1"
kind: "Service"
metadata:
  name: "users"
  labels:
    app: "users"
spec:
  selector:
    app: "users"
  ports:
    - name: "http"
      port: 9000
      protocol: "TCP"
      targetPort: 9000
      appProtocol: http
    - name: "grpc"
      protocol: "TCP"
      targetPort: 10000
      port: 10000
      appProtocol: grpc
  sessionAffinity: "None"
  type: "ClusterIP"
